### ISSUE TITLE
Bug: Unstaging all Staged file-changes resets Conflicts and exits Merging state!

### ISSUE THREAD

**Issue by goran-w** [sourcegit-scm/sourcegit#1373]
When unstaging all the Staged files (by select-all followed by "Unstage", or by "Unstage All"), a "global" `git-reset` is performed which will affect more items than the Staged ones - it has side-effects of also resetting any merge-conflicts and any ongoing "Merging" state!

Unstaging a smaller selection of Staged changes works fine, on the other hand...

NOTE: Apparently, the unstaging command now recommended by Git itself (via helpful printouts from git-status) is not `git reset <file>` but rather `git restore --staged <file>...`.

Also, the correct command for unstaging a Renamed file seems to be: `git restore --staged <new-path> <old-path>`

BTW, Un/Staging renamed files is a bit confusing (in Git, generally) :
* A file can't be Renamed while Unstaged (then it's always a Delete + Add).
* Unstaging a Renamed file splits it in two files (Deleted old-path + Added new-path), but staging these two files recreates the single Renamed file again.

**Comment by gadfly3173** [comment]
> * Unstaging a Renamed file splits it in two files (Deleted old-path + Added new-path), but staging these two files recreates the single Renamed file again.

For old files, since they are in the Git index, Git can recognize them as `DELETE` changes; for new files, even if their content remains unchanged, they are not in the Git index. Before executing `git add` (i.e., staging), Git cannot track changes in the file paths.

**Comment by love-linger** [comment]
Done.

**Comment by goran-w** [comment]
@love-linger Thanks! However, the implemented fix still does not work for `UNSTAGE ALL` (or select-all followed by `UNSTAGE`) when there are also unresolved conflicts in the Unstaged area.

When calling `restore --staged .` we get errors for the unmerged paths. There's a `--ignore-unmerged` flag, which changes these errors into warnings, but then the conflicted files will (incorrectly) become unconflicted (without actually being resolved).

It appears the only safe way is to do the unstaging for each staged file individually, even when unstaging all of them!

Additionally, we still need a fix for Unstage on a Renamed file - it should use `restore --staged <old_file> <new_file>` in order to completely unstage the Rename (resulting in a Deleted file and an Added file in the Unstaged area).

**Comment by goran-w** [comment]
@love-linger - Commit fa004ce fixes the unstaging of a Renamed file, thanks!

Remaining issue:
* In `WorkingCopy.UnstageChanges()`, the `else if (count == _staged.Count)` block needs to be deleted, to prevent that special-case optimization from either failing (without the `--ignore-unmerged`) OR messing up any current conflicts (unmerged paths)!

**Comment by love-linger** [comment]
since we do not use `--ignore-unmerged`, I think it's OK to let git handle unmerged conflicts. Using `git restore --staged .` is very common for CLI users if they want to unstage all added changes.

**Comment by goran-w** [comment]
No, it's not OK. It gives a different result from unstaging each file individually. It currently fails to unstage ANYTHING, when there are unmerged paths.

**Comment by goran-w** [comment]
Additionally, the `Discard all changes` feature is now broken, when there are unmerged paths. (This feature should still use the earlier method of git-reset, to make sure everything can be discarded!)

**Comment by goran-w** [comment]
Recent commits 78f9ae2fa9 and f1052c3efc fixed the remaining issues (in `Unstage all` and `Discard all changes`). Thanks, @love-linger!

⚠ IMPORTANT NOTE: I found out (via [forum](https://stackoverflow.com/questions/58003030/what-is-git-restore-and-how-is-it-different-from-git-reset)) that we'd better require Git version [2.25.1](https://github.com/git/git/blob/master/Documentation/RelNotes/2.25.1.adoc) whenever `git restore --staged` is used, since the following important bug was fixed there:

> "git restore --staged" did not correctly update the cache-tree structure, resulting in bogus trees to be written afterwards, which has been corrected.

For Git versions prior to that version, the earlier solution of `git reset -- <file>` could still be used (with the same caveats regarding the need for resetting the files individually, rather than by the '`.`' catch-all).

**Comment by love-linger** [comment]
Done. I've pushed a new commit that changes the minimal version of `git` required by this app to `2.25.1`

**Comment by goran-w** [comment]
> Done. I've pushed a new commit that changes the minimal version of `git` required by this app to `2.25.1`

This was done in 6e501b1. Great! All issues solved.
