### ISSUE TITLE
[Minor enhancement] Buttons missing hover-highlight (and tooltip)

### ISSUE THREAD

**Issue by goran-w** [sourcegit-scm/sourcegit#1658]
The following buttons are missing the visible hover-highlight effect that is used on other similar buttons:
* The `Home` and `Search` buttons at the top of the left sidebar.
* The small toggle-buttons for "Only highlight current branch" and "Use relative time" on the `HISTORY` view selector. (These should use the same hover-highlight as the "Show Tags as Tree" toggle-button.)

Additionally, the following buttons are missing a tooltip to display their name / description:
* The `Home` and `Search` buttons at the top of the left sidebar.
* The right-most small (3 dots, drop-down menu) button "..." on the `HISTORY` view selector.

<img width="248" height="207" alt="Image" src="https://github.com/user-attachments/assets/444fbdaa-8d86-4d52-87b7-6cc4463361a0" />

**Comment by goran-w** [comment]
@love-linger Thank you for the rapid fix! One small thing missing though - the "..." menu-dropdown button for HISTORY should also have a tooltip to explain its function ("Display Mode Options" or similar).

<img width="249" height="193" alt="Image" src="https://github.com/user-attachments/assets/2512a369-70fe-4bdf-b3dc-3574a802fcb2" />

**Comment by love-linger** [comment]
I think this is an icon commonly seen in desktop software, representing `More Options...`

**Comment by goran-w** [comment]
It's similar to this one, which has a tooltip though:

<img width="782" height="131" alt="Image" src="https://github.com/user-attachments/assets/603b0283-a19a-4474-bb1a-dbc1f2519d07" />

**Comment by goran-w** [comment]
> I think this is an icon commonly seen in desktop software, representing `More Options...`

"More Options" would work fine as a tooltip, just make sure there is one - the user expects a tooltip, since there are tooltips for the other two buttons next to it.

**Comment by love-linger** [comment]
Done

**Comment by goran-w** [comment]
Perfect!

**Comment by goran-w** [comment]
@love-linger Hmm, maybe I closed this a little too early after all - the `Dashboard` / `Search commit` tab-buttons still don't have a hover-highlight for the non-active one...

To match how the other similar tab-bars work (like the INFORMATION - CHANGES - FILES switcher), the active (blue) button can stay untouched but the non-active (grayish) one should become highlighted when hovered!

**Comment by goran-w** [comment]
Perfect, now it's great!

**Comment by goran-w** [comment]
@ozmium Could you please post this question / suggestion in a new issue, instead of adding it to this unrelated and already closed issue? 😉 

Also, the image you posted is not viewable...
