### ISSUE TITLE
[BUG] The user cannot select multiple lines of text in the Git message Text Field

### ISSUE THREAD

**Issue by ozmium** [sourcegit-scm/sourcegit#394]
SourceGit is very useful and has lots of features. However, it's not possible to select all text in the Git message field, when the text has lots of new line characters that require vertical scrolling. This problem happens on the "INFORMATION" panel that shows a historical git message.

The problem happens on Linux and MacOS, and possibly Windows.

### Steps to reproduce the bug, using SourceGit 8.26

1. Make a commit that has at least 30 lines of text (use 30 new line characters in the message).
2. Make the "INFORMATION" panel small, so that only 10-15 lines are displayed.
3. Try to select all the text.
4. Optional: Try to select lines 3-30.
5. Optional: Repeat these steps in the text editor, when trying to write a long message for the Git commit.

### Expected Result

This is how it should work - Screen recording video from SourceTree Git client.

https://github.com/user-attachments/assets/b24f4b89-ac19-469e-bc72-e453b4bf3228

1. The Text View should not jump unexpectedly, while selecting text.
2. To allow more selection, the Text View should auto-scroll when the mouse is near the bottom or the top.
3. It should be easy to start selecting text, using the obvious mouse click locations.
4. SourceGit should behave like other desktop apps that allow text selections across multiple lines.

### Actual Result

This is how it works in SourceGit.

https://github.com/user-attachments/assets/2e46b143-d058-4921-bf32-b0d89ea11ed8

There are 4 big problems, as shown in the video:

1. At 00:04, when trying to select the top of the text, **the Text View jumps unexpectedly upwards**. This is bad because the user doesn't know what's going on. Text Views should not move their position and jump around randomly, when the user is trying to start selecting some text at a specific position. It causes lots of confusion as well.
2. **Not all lines can be selected**, whether you try from the top or the bottom. This is because **the Text View does not start scrolling, when the mouse moves to the bottom of it**. It should do, like SourceTree does (and all other apps do).
3. At 00:20, **it's difficult to start a text selection, because the Text View is not responding properly to the mouse click locations**. It takes 3 attempts to start the text selection, which is too much, and a burden. This problem happens at the top as well.
4. **SourceGit does not behave like other desktop apps** that allow text selection.
5. The user has to use a different Git client in order to copy all the text of a long Git message.
6. Not shown in the video: When some text is selected across multiple lines, it's difficult to unselect it. This often requires 2-3 mouse clicks, when it should only need 1 click or drag.

**Comment by love-linger** [comment]
I've pushed a commit that add a context menu item for `SelectableTextBlock` that allows user copy entire content by single click.
<img width="632" alt="image" src="https://github.com/user-attachments/assets/600ee5c5-7f60-4c9d-a71a-e8089c770aed">

**Comment by ozmium** [comment]
That's fine. It's a good first start. Thank you. 👍

However, it doesn't fix this item:

> 4. Optional: Try to select lines 3-30.

The intention is that the user wants to select a large part of text across multiple lines, not always select all the text.

**Comment by love-linger** [comment]
it's hard to implement auto scroll for the CommitDetail control, because when you are selecting text, the pointer(mouse) is captured by the SelectableTextBlock. Currently, I have no idea how to do it.

You can select part of the text, then scroll the panel using mouse wheel, then hold `Shift` to continue the selection.

**Comment by love-linger** [comment]
I've pushed a new commit that supports auto scrolling while seleting text in commit message.
