### ISSUE TITLE
[ENHANCEMENT] - Blame commit selection

### ISSUE THREAD

**Issue by Shimoon** [sourcegit-scm/sourcegit#448]
# Proposal
In the blame view, it could be nice if we could select a commit in the left side bar and highlight all the involved lines for this particular commit instead of only relying on SHA and author date.
It could be easier to quickly identify one commit in the file, also having selection that stick would allow scrolling through the file without losing focus.

*I know we can click on the commit hash and see the changes in the diff view but I am not talking about viewing diff and since the blame view exists, it would be very useful to improve it by highlighting this information right there.*

# Mockup
![sourcegit_blame_highlight_selection](https://github.com/user-attachments/assets/58ec7502-377e-4542-b70e-2831806b06d9)

**Comment by love-linger** [comment]
added:

![image](https://github.com/user-attachments/assets/d5811668-06c5-402b-b773-750633ec42ed)

You can download the latest build from Github Action

**Comment by Shimoon** [comment]
Thank you for tackle this feature so rapidly @love-linger !
However after testing the action #1238 (commit [2430175](https://github.com/sourcegit-scm/sourcegit/commit/24301751d3a94a85062e5786a5438ae6b026482e)), the selection doesn't seems to properly hold (slide) and I have difficulties to select back the commit after scrolling
*(see joined gif)*
![sourcegit_blame_selection_issue](https://github.com/user-attachments/assets/e90d41fe-2db2-4010-85c9-50ba56c336df)

This issue is closed now, tell me if it's better to open a new one for this.

**Comment by love-linger** [comment]
You should change selection by click the text editor not the commit info.

**Comment by love-linger** [comment]
What OS do you using?

**Comment by love-linger** [comment]
Fixed. You can try the latest build.

**Comment by love-linger** [comment]
It is because that the highlighted background did not update when the text area lost focus.

**Comment by Shimoon** [comment]
Oh sorry, nvm @love-linger.. I've still have the same issue but only if I scroll to the very top of the file.
I'm on Windows 10.
![sourcegit_blame_selection_issue2](https://github.com/user-attachments/assets/8296a144-81ca-4fae-a9f7-bb06defe3928)

**Comment by love-linger** [comment]
I can see when you are scrolling, the highlight background is not updated (following with the scroll)

**Comment by love-linger** [comment]
The expected result is

https://github.com/user-attachments/assets/6b7c91d9-51fb-4185-a882-c98cd2af41a4

**Comment by Shimoon** [comment]
> I can see when you are scrolling, the highlight background is not updated (following with the scroll)

Yes, it does work well if I select a commit further down the file and scroll around though. The issue seems to be trigger when I reach the very top.

**Comment by love-linger** [comment]
I can not reproduce this issue. The `OnTextAreaLayoutUpdated` event works fine on my PC & mac

**Comment by love-linger** [comment]
You can try the latest build.

**Comment by Shimoon** [comment]
Seems to be fixed on my end ! 😄
Thanks !
