### ISSUE TITLE
ConfigureWorkspace window displays incomplete

### ISSUE THREAD

**Issue by gadfly3173** [sourcegit-scm/sourcegit#458]
![image](https://github.com/user-attachments/assets/8d127a74-21d3-42fd-89eb-12f1e87c52b4)

**Comment by love-linger** [comment]
Would you like to help me checking out the width and height of the right column?
![image](https://github.com/user-attachments/assets/0c8dca65-d4e8-4801-9351-129534243ddb)

**Comment by gadfly3173** [comment]
> Would you like to help me checking out the width and height of the right column? 

216, 0, 236, 324

**Comment by love-linger** [comment]
> > Would you like to help me checking out the width and height of the right column?
> 
> 216, 0, 236, 324

Thanks very much. The width is too small.

**Comment by love-linger** [comment]
done.

**Comment by gadfly3173** [comment]
![image](https://github.com/user-attachments/assets/68414913-8cbc-4dc7-a42f-b0a04de34936)
Seems still not correct on my Deepin V23.

**Comment by love-linger** [comment]
Can you provide the width of `Workspaces` window? It should be 
![image](https://github.com/user-attachments/assets/41ddf20b-c337-4fe4-8c92-535907a1d26f)

**Comment by gadfly3173** [comment]
This patch would be good.

```diff
diff --git a/src/Views/ConfigureWorkspace.axaml b/src/Views/ConfigureWorkspace.axaml
index 95b7e91..e245032 100644
--- a/src/Views/ConfigureWorkspace.axaml
+++ b/src/Views/ConfigureWorkspace.axaml
@@ -11,12 +11,12 @@
                     x:DataType="vm:ConfigureWorkspace"
                     x:Name="ThisControl"
                     Icon="/App.ico"
                     Title="{DynamicResource Text.ConfigureWorkspace}"
-                    Width="494" SizeToContent="Height"
+                    SizeToContent="WidthAndHeight"
                     CanResize="False"
                     WindowStartupLocation="CenterOwner">
-  <Grid RowDefinitions="Auto,Auto">
+  <Grid RowDefinitions="Auto,Auto" MinWidth="494">
     <!-- TitleBar -->
     <Grid Grid.Row="0" ColumnDefinitions="Auto,*,Auto" Height="30" IsVisible="{Binding !#ThisControl.UseSystemWindowFrame}">
       <Border Grid.Column="0" Grid.ColumnSpan="3"
               Background="{DynamicResource Brush.TitleBar}"

```

**Comment by love-linger** [comment]
closed by #460
