### ISSUE TITLE
Wrong column indentation on right side of Interactive Rebase window, for wide commit messages

### ISSUE THREAD

**Issue by goran-w** [sourcegit-scm/sourcegit#764]
This happens for lines where the commit message (title) is wider than its column.

![image](https://github.com/user-attachments/assets/dfb0b3a3-c41e-41e5-8e67-087697e861db)

**Comment by love-linger** [comment]
Fixed. You can download the latest CI build from Github Action.

**Comment by goran-w** [comment]
Thanks! Looks less pronounced, but the issue is still there? (I built from source, on 807cec8.)
![image](https://github.com/user-attachments/assets/df2a6f19-dfed-4649-ba97-fd8dd958efbd)

**Comment by love-linger** [comment]
![image](https://github.com/user-attachments/assets/c0c76700-d19c-4820-8f8a-07a0c662a73c)

**Comment by goran-w** [comment]
I'm afraid it's still not completely fixed. 😢 (Built from source, on 400aaac.)
Here I tried to match your latest screenshot:
![image](https://github.com/user-attachments/assets/8070b6cb-8853-4532-b061-6421f1499588)

**Comment by aikawayataro** [comment]
I've succeed to reproduce this with font sizes >12 e.g. 13 or 14, both Linux and Windows

**Comment by love-linger** [comment]
I reproduce this issue in @aikawayataro's way. Please try the commit e65ac18afc55f69741e6bd3788f5c485c89e7a56 to see if it is solved.

**Comment by love-linger** [comment]
Please update to commit 938876e92478b07c64638254faef2b5a0393cc2d

**Comment by goran-w** [comment]
Thanks, @love-linger - now it's solved! 🥇

NOTE: Maybe there should be a slight margin/padding at the left and right sides of the list rows? (The narrow scroll indicator renders over the up/down arrows on the right side and the drag-handles on the left side look a bit crammed as well.)

![image](https://github.com/user-attachments/assets/289cec96-5351-47c8-97a6-2a2d9bfc052a)

**Comment by goran-w** [comment]
Thank you, looks perfect! Closing the issue.
